spring.main.banner-mode: off

server.error.whitelabel.enabled: false

logging.level:
  org.springframework: ERROR
  org.elasticsearch: ERROR
  org.hibernate: ERROR
  io.undertow: ERROR
  org.xnio: ERROR
  org.apache: ERROR
  org.jboss: ERROR

pebble.cache: false

covid.json.url: 'https://opendata.ecdc.europa.eu/covid19/casedistribution/json/'

app.jsonUrl: 'https://opendata.ecdc.europa.eu/covid19/casedistribution/json/'

covid.csv.url: 'https://opendata.ecdc.europa.eu/covid19/casedistribution/csv/'
